### ISSUE TITLE
10/12-10/16, 2020 standups

### ISSUE THREAD

**Issue by asheren** [asheren/asheren.github.io#96]
link to last week: link here

Plan for the week (from monday's meeting)

NOTES HERE FROM WHAT THE PLAN WAS

**Comment by asheren** [comment]
10/12

github:

vscs:

vs code:

**Comment by asheren** [comment]
10/13

Github:

vscs:

vs code:

**Comment by dougam** [comment]
The only thing I don't like about this is that you have to scroll down to see the latest and you would have an entry for each reporting team, correct?

**Comment by asheren** [comment]
@dougam folks can edit comments so we can have 1 comment per day and sections for each reporting tem.
